//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace MediRegist.WebReference1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Mhs5serviceSoap11Binding", Namespace="http://service.communication.service.dareway.com")]
    public partial class Mhs5service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback loginByYybmOperationCompleted;
        
        private System.Threading.SendOrPostCallback invokeCottonOperationCompleted;
        
        private System.Threading.SendOrPostCallback dipInvokeOperationCompleted;
        
        private System.Threading.SendOrPostCallback pipInvokeOperationCompleted;
        
        private System.Threading.SendOrPostCallback invokeOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback invokeSiOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Mhs5service() {
            this.Url = global::MediRegist.Properties.Settings.Default.yb_upload_WebReference1_Mhs5service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event loginByYybmCompletedEventHandler loginByYybmCompleted;
        
        /// <remarks/>
        public event invokeCottonCompletedEventHandler invokeCottonCompleted;
        
        /// <remarks/>
        public event dipInvokeCompletedEventHandler dipInvokeCompleted;
        
        /// <remarks/>
        public event pipInvokeCompletedEventHandler pipInvokeCompleted;
        
        /// <remarks/>
        public event invokeCompletedEventHandler invokeCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event invokeSiCompletedEventHandler invokeSiCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:loginByYybm", RequestNamespace="http://Mhs5service.dareway.com", ResponseNamespace="http://Mhs5service.dareway.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string loginByYybm([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args2) {
            object[] results = this.Invoke("loginByYybm", new object[] {
                        args0,
                        args1,
                        args2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginByYybmAsync(string args0, string args1, string args2) {
            this.loginByYybmAsync(args0, args1, args2, null);
        }
        
        /// <remarks/>
        public void loginByYybmAsync(string args0, string args1, string args2, object userState) {
            if ((this.loginByYybmOperationCompleted == null)) {
                this.loginByYybmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginByYybmOperationCompleted);
            }
            this.InvokeAsync("loginByYybm", new object[] {
                        args0,
                        args1,
                        args2}, this.loginByYybmOperationCompleted, userState);
        }
        
        private void OnloginByYybmOperationCompleted(object arg) {
            if ((this.loginByYybmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginByYybmCompleted(this, new loginByYybmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:invokeCotton", RequestNamespace="http://Mhs5service.dareway.com", ResponseNamespace="http://Mhs5service.dareway.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string invokeCotton([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args5) {
            object[] results = this.Invoke("invokeCotton", new object[] {
                        args0,
                        args1,
                        args2,
                        args3,
                        args4,
                        args5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invokeCottonAsync(string args0, string args1, string args2, string args3, string args4, string args5) {
            this.invokeCottonAsync(args0, args1, args2, args3, args4, args5, null);
        }
        
        /// <remarks/>
        public void invokeCottonAsync(string args0, string args1, string args2, string args3, string args4, string args5, object userState) {
            if ((this.invokeCottonOperationCompleted == null)) {
                this.invokeCottonOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvokeCottonOperationCompleted);
            }
            this.InvokeAsync("invokeCotton", new object[] {
                        args0,
                        args1,
                        args2,
                        args3,
                        args4,
                        args5}, this.invokeCottonOperationCompleted, userState);
        }
        
        private void OninvokeCottonOperationCompleted(object arg) {
            if ((this.invokeCottonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invokeCottonCompleted(this, new invokeCottonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:dipInvoke", RequestNamespace="http://Mhs5service.dareway.com", ResponseNamespace="http://Mhs5service.dareway.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string dipInvoke([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args2) {
            object[] results = this.Invoke("dipInvoke", new object[] {
                        args0,
                        args1,
                        args2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void dipInvokeAsync(string args0, string args1, string args2) {
            this.dipInvokeAsync(args0, args1, args2, null);
        }
        
        /// <remarks/>
        public void dipInvokeAsync(string args0, string args1, string args2, object userState) {
            if ((this.dipInvokeOperationCompleted == null)) {
                this.dipInvokeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndipInvokeOperationCompleted);
            }
            this.InvokeAsync("dipInvoke", new object[] {
                        args0,
                        args1,
                        args2}, this.dipInvokeOperationCompleted, userState);
        }
        
        private void OndipInvokeOperationCompleted(object arg) {
            if ((this.dipInvokeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dipInvokeCompleted(this, new dipInvokeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:pipInvoke", RequestNamespace="http://Mhs5service.dareway.com", ResponseNamespace="http://Mhs5service.dareway.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string pipInvoke([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args5) {
            object[] results = this.Invoke("pipInvoke", new object[] {
                        args0,
                        args1,
                        args2,
                        args3,
                        args4,
                        args5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pipInvokeAsync(string args0, string args1, string args2, string args3, string args4, string args5) {
            this.pipInvokeAsync(args0, args1, args2, args3, args4, args5, null);
        }
        
        /// <remarks/>
        public void pipInvokeAsync(string args0, string args1, string args2, string args3, string args4, string args5, object userState) {
            if ((this.pipInvokeOperationCompleted == null)) {
                this.pipInvokeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpipInvokeOperationCompleted);
            }
            this.InvokeAsync("pipInvoke", new object[] {
                        args0,
                        args1,
                        args2,
                        args3,
                        args4,
                        args5}, this.pipInvokeOperationCompleted, userState);
        }
        
        private void OnpipInvokeOperationCompleted(object arg) {
            if ((this.pipInvokeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pipInvokeCompleted(this, new pipInvokeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:invoke", RequestNamespace="http://Mhs5service.dareway.com", ResponseNamespace="http://Mhs5service.dareway.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string invoke([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args4) {
            object[] results = this.Invoke("invoke", new object[] {
                        args0,
                        args1,
                        args2,
                        args3,
                        args4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invokeAsync(string args0, string args1, string args2, string args3, string args4) {
            this.invokeAsync(args0, args1, args2, args3, args4, null);
        }
        
        /// <remarks/>
        public void invokeAsync(string args0, string args1, string args2, string args3, string args4, object userState) {
            if ((this.invokeOperationCompleted == null)) {
                this.invokeOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvokeOperationCompleted);
            }
            this.InvokeAsync("invoke", new object[] {
                        args0,
                        args1,
                        args2,
                        args3,
                        args4}, this.invokeOperationCompleted, userState);
        }
        
        private void OninvokeOperationCompleted(object arg) {
            if ((this.invokeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invokeCompleted(this, new invokeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:login", RequestNamespace="http://Mhs5service.dareway.com", ResponseNamespace="http://Mhs5service.dareway.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string login([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args1) {
            object[] results = this.Invoke("login", new object[] {
                        args0,
                        args1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string args0, string args1) {
            this.loginAsync(args0, args1, null);
        }
        
        /// <remarks/>
        public void loginAsync(string args0, string args1, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        args0,
                        args1}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:invokeSi", RequestNamespace="http://Mhs5service.dareway.com", ResponseNamespace="http://Mhs5service.dareway.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string invokeSi([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string args4) {
            object[] results = this.Invoke("invokeSi", new object[] {
                        args0,
                        args1,
                        args2,
                        args3,
                        args4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invokeSiAsync(string args0, string args1, string args2, string args3, string args4) {
            this.invokeSiAsync(args0, args1, args2, args3, args4, null);
        }
        
        /// <remarks/>
        public void invokeSiAsync(string args0, string args1, string args2, string args3, string args4, object userState) {
            if ((this.invokeSiOperationCompleted == null)) {
                this.invokeSiOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvokeSiOperationCompleted);
            }
            this.InvokeAsync("invokeSi", new object[] {
                        args0,
                        args1,
                        args2,
                        args3,
                        args4}, this.invokeSiOperationCompleted, userState);
        }
        
        private void OninvokeSiOperationCompleted(object arg) {
            if ((this.invokeSiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invokeSiCompleted(this, new invokeSiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void loginByYybmCompletedEventHandler(object sender, loginByYybmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginByYybmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginByYybmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void invokeCottonCompletedEventHandler(object sender, invokeCottonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invokeCottonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invokeCottonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void dipInvokeCompletedEventHandler(object sender, dipInvokeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dipInvokeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dipInvokeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void pipInvokeCompletedEventHandler(object sender, pipInvokeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pipInvokeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pipInvokeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void invokeCompletedEventHandler(object sender, invokeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invokeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invokeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void invokeSiCompletedEventHandler(object sender, invokeSiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invokeSiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invokeSiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591